### PR TITLE
added the view code contributions page

### PR DESCRIPTION
**Pull request by kemsguy7**
https://github.com/ChallengeForge/TheWeeklyChallenge/assets/31693594/64c5f1b9-7267-4aeb-9760-b98fa02a18fe

## Description

In this PR, I created the view code contributions page where users can view code snippets from contribution of other users, I also added a comment section and a syntax highlighter to complete the stated requirements.

## Type of Change

- [ x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Changes

Please which part of the project your changes affect ?
- [ x] Frontend (Templates, CSS, JS)
- [ ] Backend (Dancer2, api-docs, Dockerfile)

### CODE REVIEW

**Comment by kemsguy7** [comment]
@manwar , kindly review, thanks.

**Review by manwar — COMMENTED** [review]
Merging now, will review the layout later.

**Comment by manwar** [comment]
Thanks for your contributions. @kemsguy7

**Comment by kemsguy7** [comment]
> Thanks for your contributions. @kemsguy7

You're welcome @manwar

**Pull request merged**
