### PR TITLE
Admin mailing list

### PR DESCRIPTION
**Pull request by kemsguy7**
## Description

In this PR, I added the admin mailing page, in this page, an admin can view all the data users from a database and create a mailing list based on the number checked in one of the checkboxes. Also, admin can delete users from the mailing list with delete buttons provided on the page

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Changes

Please which part of the project your changes affect?
- [ x

https://github.com/ChallengeForge/TheWeeklyChallenge/assets/31693594/970a4ac0-58ea-467f-955c-5f2521ce31bb

] Frontend (Templates, CSS, JS)
- [ ] Backend (Dancer2, api-docs, Dockerfile)

### CODE REVIEW

**Comment by kemsguy7** [comment]
@manwar , here is the admin mailing list page, kindly review, thanks

**Comment by manwar** [comment]
@kemsguy7 I don't see header and footer?

Also the section where you have email adress and delete button, please show list of email addres, depending what you selected in the radio button.

**Comment by kemsguy7** [comment]
> @kemsguy7 I don't see header and footer?
> 
> Also the section where you have email adress and delete button, please show list of email addres, depending what you selected in the radio button.

It's all part of the admin dashboard,  @soniyaprasad77 

> @kemsguy7 I don't see header and footer?
> 
> Also the section where you have email adress and delete button, please show list of email addres, depending what you selected in the radio button.

Okay, applying that now

**Review by manwar — COMMENTED** [review]
Merging now, will review layout later. Thanks.

**Comment by manwar** [comment]
Thanks for your contributions. @kemsguy7

**Comment by manwar** [comment]
@kemsguy7 This layout is not what we discussed in Slack, right? Please check.

**Pull request merged**
