### PR TITLE
User dashboard

### PR DESCRIPTION
**Pull request by kemsguy7**
## Description
I updated the user dashboard with a view comments page, replies page and notifications page. 

https://github.com/ChallengeForge/TheWeeklyChallenge/assets/31693594/88594392-bf36-42fd-adad-13ff04ae1e0e

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Changes

Please which part of the project your changes affect ?
- [x] Frontend (Templates, CSS, JS)
- [ ] Backend (Dancer2, api-docs, Dockerfile)

### CODE REVIEW

**Comment by kemsguy7** [comment]
@manwar , I made updates to the user dashboard as per the full requirements stated, kindly review and merge.

**Comment by manwar** [comment]
@kemsguy7 I don't see header and footer?

**Comment by kemsguy7** [comment]
> @kemsguy7 I don't see header and footer?

Ok mentor, i'll update it

**Comment by manwar** [comment]
@kemsguy7 any update on this?

**Review by manwar — COMMENTED** [review]
Merging now, will review layout later.

**Comment by manwar** [comment]
Thanks for your contributions. @kemsguy7

**Comment by manwar** [comment]
@kemsguy7 Layout seems to be messed up.
Capture

**Pull request merged**
