### PR TITLE
chore(migration): migrate `json` data to `mysql` db using `perl` scripts

### PR DESCRIPTION
**Pull request by baimamboukar**
This Pull Request closes #143 in https://github.com/manwar/theweeklychallenge/issues/143 by migrating the `users.json` and `members.json` to the `mysql` database according to the defined `schema`

### There are more details about this PR:
- It parses the `json` data files and extracts relevant data (username and fullname)
- It determines the `user_type` then assigns a default password to the user
- The default password, `password` is `hashed` and user data is saved to `db`

### Screenshoot of users table

Screen Shot 2024-03-18 at 03 11 38

### CODE REVIEW

**Comment by baimamboukar** [comment]
Hello mentor @manwar 👋
I trust you are doing well 🙂

It is me again 😅
I think this `PR` is ready for review.

**Comment by manwar** [comment]
@baimamboukar please move perl package to lib/ folder.
Also make sure package name should match the file name.

**Comment by baimamboukar** [comment]
Hello @manwar 👋

The requested changes have been added. Thanks for reviewing again

**Comment by manwar** [comment]
Thanks @baimamboukar for your contributions.

**Pull request merged**
