### PR TITLE
User dashboard

### PR DESCRIPTION
**Pull request by kemsguy7**
https://github.com/ChallengeForge/TheWeeklyChallenge/assets/31693594/a4e5685e-880c-474d-9130-c502b97f8f4e

## Type of Change

- [x]✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Changes

Please which part of the project your changes affect ?
- [ x] Frontend (Templates, CSS, JS)
- [ ] Backend (Dancer2, api-docs, Dockerfile)

### CODE REVIEW

**Comment by kemsguy7** [comment]
@manwar I've made updates, kindly review

**Comment by kemsguy7** [comment]
https://github.com/ChallengeForge/TheWeeklyChallenge/assets/31693594/91efc52c-5c38-4e1a-82c2-24178f7e03ad
@manwar I've updated this PR, kindly review it, thanks.

**Review by manwar — COMMENTED** [review]
Merged, will review layout later.

**Comment by manwar** [comment]
Thanks for your contributions. @kemsguy7

**Comment by kemsguy7** [comment]
> Thanks for your contributions. @kemsguy7

You're welcome mentor

**Pull request merged**
