### PR TITLE
User dashboard

### PR DESCRIPTION
**Pull request by kemsguy7**
## Description

In this task, I created the user dashboard and added dummy links to future pages that will be linked to the dashboard. The user dashboard has functionalities such as Comments, replies, notifications and viewing contribution statistics.  Also, there are charts showing statics for general contributions and contributions of a logged-in user.

## Type of Change

- [X ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Changes

Please which part of the project your changes affect ?
- [X ] Frontend (Templates, CSS, JS)
- [ ] Backend (Dancer2, api-docs, Dockerfile)

### CODE REVIEW

**Comment by kemsguy7** [comment]
@manwar kindly review.
For the comment and reply system, I plan to add separate pages where a user can view all contributions and perform actions such as editing and replying to comments.

Also, I will add a page that shows Notifications, kindly let me know your inputs

**Review by manwar — COMMENTED** [review]
Good job, will review the page after merge.

**Comment by manwar** [comment]
Thanks for your contributions. @kemsguy7

**Comment by kemsguy7** [comment]
> Good job, will review the page after merge.

Thank you mentor Please have you had time to review it and thought about my proposition too?

**Pull request merged**
