### PR TITLE
Feature/website minor update

### PR DESCRIPTION
**Pull request by NoubissiViany**
## Description

-Remove one logo from header pages

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Changes

Please which part of the project your changes affect ?

- [x] Frontend (Templates, CSS, JS)
- [ ] Backend (Dancer2, api-docs, Dockerfile)

### CODE REVIEW

**Comment by himanshipikachu** [comment]
@NoubissiViany Please attach screenshots of the changes or else its hard to review your changes

**Comment by NoubissiViany** [comment]
@himanshisrestha I didn't attach a video on this one because I modified all the header pages from two logo to one. As a result, I decided to send it without the video since the description is clear

**Comment by himanshipikachu** [comment]
@NoubissiViany As we are at the end of frontend work of the prototype , to confirm all the changes a video is required as we don't want last minute hiccups in the prototype after merging the PR into the main , just by looking at the description the changes can't be cross checked 🥲. If you are not able to attach the video due to size restrictions please send it in the group.

**Comment by NoubissiViany** [comment]
@himanshisrestha Okay well received

**Review by manwar — COMMENTED** [review]
Good job.

**Comment by manwar** [comment]
Thanks for the cleanup. @NoubissiViany

**Comment by NoubissiViany** [comment]
@manwar you are welcome

**Pull request merged**
