### PR TITLE
chore(docker): Dockerize `backend` and update docs to include `how to` run app's docker image

### PR DESCRIPTION
**Pull request by baimamboukar**
## Description

This pull request updates the backend's Docker containerization setup and adds a documentation guildeline on how to get the development server running on your `localhost`.

The following changes were made
- Added a `.dockerignore` file to exclude unnecessary files from the Docker image.
- Updated the `Dockerfile` to install dependencies and match the new project directory structure.
- Improved the `README.md` documentation to provide clear instructions for building and running the Docker image.

These updates simplify the process of building and running the backend code in a Docker container, reducing setup time and improving developer workflow.

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [x] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [x] ✅ Build configuration change
- [x] 📝 Documentation
- [x] 🗑️ Chore

## Changes

Please which part of the project your changes affect ?

- [ ] Frontend (Templates, CSS, JS)
- [x] Backend (Dancer2, api-docs, Dockerfile)

### CODE REVIEW

**Comment by baimamboukar** [comment]
Hello @manwar 👋
This is ready for review.

**Review by manwar — COMMENTED** [review]
Brilliant work, well documented.

**Comment by manwar** [comment]
Impressive work, keep it up. @baimamboukar

**Comment by baimamboukar** [comment]
> Impressive work, keep it up. @baimamboukar 

Thanks very much @manwar ✨
It is a pleasure 🫡✨

**Pull request merged**
