### PR TITLE
fixes #136 admins dashboard

### PR DESCRIPTION
**Pull request by soniyadotp**
adminsdashboard

### CODE REVIEW

**Comment by manwar** [comment]
@soniyaprasad77 are you going to update the menus?

**Comment by soniyadotp** [comment]
Yea, I will keep on working even after the merge, like adjusting acc to the needs, what' changes do you want me to incorporate as of now?

**Comment by manwar** [comment]
@soniyaprasad77 layout looks fine to me, we can fine tune a bit later, right?

**Comment by soniyadotp** [comment]
Yes, since this is a prototype, we need to continuously update the UI based on various factors, such as feedback from the backend team, and I'm fully committed to adapting and refining it as required.

**Comment by soniyadotp** [comment]
Please checkout, as I have moved the files.

**Pull request merged**
