### PR TITLE
Implementing GitHub Action for PerlCritic 

### PR DESCRIPTION
**Pull request by joshuagaladima**
## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [x] 🗑️ Chore

## Changes

Please which part of the project your changes affect ?

- [ ] Frontend (Templates, CSS, JS)
- [x] Backend (Dancer2, api-docs, Dockerfile)

### CODE REVIEW

**Review by manwar — COMMENTED** [review]
Good addition.

**Comment by manwar** [comment]
@joshuagaladima please fix the check failure.

**Comment by joshuagaladima** [comment]
> @joshuagaladima please fix the check failure.

Alright @manwar

**Comment by manwar** [comment]
Thanks for your contributions. @joshuagaladima

**Pull request merged**
