### PR TITLE
Created sign-in page 

### PR DESCRIPTION
**Pull request by prakmaurya**
Created the sign-in page(html, css and js). This will let user login or create new account. Clicking on logo icon in header will redirect to home page and this page will be linked to "Sign-in" option in navbar or menu.

### CODE REVIEW

**Comment by manwar** [comment]
@prakmaurya I don't see the captcha on this page?

**Comment by prakmaurya** [comment]
@manwar I will include that as well. The captcha will be required during login and sign up both right? Please review and suggest any more changes that are required.

**Comment by manwar** [comment]
@prakmaurya Yes, it would be required for both login and sign up.

**Comment by manwar** [comment]
Well done @prakmaurya

**Comment by prakmaurya** [comment]
@manwar Thanks for the quick response . I hope this would speed up the issues of backend creation using dancer2. Please share any suggestions you would like to add :)

**Pull request merged**
