### PR TITLE
Minor chnages

### PR DESCRIPTION
**Pull request by fahad-albasrawie**
I changed the color and applied the new design color.

### CODE REVIEW

**Comment by manwar** [comment]
@fahad-albasrawie do we need this?

**Comment by fahad-albasrawie** [comment]
Dear mentor @manwar, we do need it actually. Although it has a conflict, we can skip this commit change called "Minor Changes" but the last commit works fine and it is needed.

**Comment by manwar** [comment]
@fahad-albasrawie which commit to skip?

**Comment by fahad-albasrawie** [comment]
The **this Minor chnages #20** I made yesterday because of you said: **"do we need this?"**.

**Comment by manwar** [comment]
@fahad-albasrawie I tried my best to resolve the conflicts. Please check if it still works.

**Pull request merged**
