### PR TITLE
Admin mailing list

### PR DESCRIPTION
**Pull request by kemsguy7**
https://github.com/ChallengeForge/TheWeeklyChallenge/assets/31693594/a1591043-a145-4be3-b193-73e6b06ace7a

## Type of Change

- [ x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Changes

Please which part of the project your changes affect ?
- [ x] Frontend (Templates, CSS, JS)
- [ ] Backend (Dancer2, api-docs, Dockerfile)

### CODE REVIEW

**Comment by kemsguy7** [comment]
@manwar kindly review, I've applied updates to suit your specification

**Review by manwar — COMMENTED** [review]
Merging now, will review the layout soon.

**Comment by manwar** [comment]
Thanks @kemsguy7

**Comment by kemsguy7** [comment]
> Thanks @kemsguy7

You're welcome sir

**Comment by manwar** [comment]
@kemsguy7 can you get rid of the horizontal and vertical scroll bar?
Capture

**Pull request merged**
