### PR TITLE
Rss feed

### PR DESCRIPTION
**Pull request by kemsguy7**
## Description

In this PR, I created the RSS feeds page 

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Changes

Please which part of the project your changes affect ?
- [x

https://github.com/ChallengeForge/TheWeeklyChallenge/assets/31693594/25766956-b679-4825-94c0-f7be35bc8f89

] Frontend (Templates, CSS, JS)
- [ ] Backend (Dancer2, api-docs, Dockerfile)

### CODE REVIEW

**Comment by kemsguy7** [comment]
@manwar kindly review, thanks.

**Comment by manwar** [comment]
@kemsguy7 Good design. However there is going to be just one RSS feed and we don't want search feature.

**Comment by kemsguy7** [comment]
RSS FEED
@manwar , I've applied changes from feedback. Kindly review

**Comment by manwar** [comment]
@kemsguy7 Perfect, just remove the title "All the latest feeds" as it no longer relevant since we have only one feed.

**Comment by kemsguy7** [comment]
Screenshot 2024-03-24 at 20 12 37

@manwar i've updated it

**Review by manwar — COMMENTED** [review]
Good job.

**Comment by manwar** [comment]
Thanks for your contributions. @kemsguy7

**Comment by manwar** [comment]
@kemsguy7 The title is still there when I merged it. Your attached screenshot didn't have it, though. I am not sure what is going on here.

**Comment by kemsguy7** [comment]
> @kemsguy7 The title is still there when I merged it. Your attached screenshot didn't have it, though. I am not sure what is going on here.

@manwar Please which title is that sir? I can't seem to find anything, can you please share a screenshot?

**Comment by kemsguy7** [comment]
> Thanks for your contributions. @kemsguy7
You're welcome sir.

**Comment by manwar** [comment]
@kemsguy7 This is what I am talking about.
Capture

**Pull request merged**
