### PR TITLE
added updates to view contributions  and search_contributions pages

### PR DESCRIPTION
**Pull request by kemsguy7**
https://github.com/ChallengeForge/TheWeeklyChallenge/assets/31693594/f34f41e9-8281-4011-95d7-9ee3db46ecbd

ections.mp4…

## Description

I applied feedback gotten from the last pr on both the search contributions and view contributions page 

## Type of Change

- [ x] ✨ New feature (non-breaking change which adds functionality)
- [x ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Changes

Please which part of the project your changes affect ?
- [ x] Frontend (Templates, CSS, JS)
- [ ] Backend (Dancer2, api-docs, Dockerfile)

### CODE REVIEW

**Comment by kemsguy7** [comment]
@manwar, kindly review, I added the changes you requested for, kindly review.

**Review by manwar — COMMENTED** [review]
Good job, merging now, will review layout later.

**Comment by manwar** [comment]
Thanks for your contributions. @kemsguy7

**Comment by kemsguy7** [comment]
> Good job, merging now, will review layout later.

Thank you mentor @manwar

**Pull request merged**
