### PR TITLE
chore(ci): nicely formatted files and add a `github action` workflow to automate formating

### PR DESCRIPTION
**Pull request by baimamboukar**
## Description

This pull request enhances the project's code `quality` and developer `experience` by

- Improved Code Formatting: Enforces consistent and beautiful code formatting throughout the project. This improves code readability and maintainability for all developers.
- Automated Formatting Workflow: Introduces a GitHub Action `workflow` to automate code formatting. This ensures consistent formatting remains effortless to maintain, saving time and reducing the risk of human error.

By implementing these improvements, this pull request lays the foundation for a well-organized and easy-to-contribute-to codebase.

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Changes

Please which part of the project your changes affect ?
- [x] Frontend (Templates, CSS, JS)
- [ ] Backend (Dancer2, api-docs, Dockerfile)

### CODE REVIEW

**Comment by baimamboukar** [comment]
Hey @manwar 👋

As I was going through the prototype's codebase again, I realized that the files were not consistently formatted. So I decided to introduce these changes. I believe this could improve the code's readability for all.

Thanks for reviewing.

**Comment by manwar** [comment]
@baimamboukar please resolve the conflicts as I have no clue what to keep and what ti ignore.

**Comment by baimamboukar** [comment]
Hello 👋 

Alright @manwar mentor
I'm on it.

**Comment by baimamboukar** [comment]
Hello @manwar 

The conflicts have been resolved already ✅

**Review by manwar — COMMENTED** [review]
Good job.

**Comment by manwar** [comment]
Good catch and thanks for your contributions. @baimamboukar

**Pull request merged**
