### PR TITLE
Optimised db schema

### PR DESCRIPTION
**Pull request by soniyadotp**
In this pull request (PR), several optimizations and improvements have been made to the schema:

1. Introducing the roles table (using ENUM) and removing unnecessary tables:

```sql
role ENUM('admin', 'member', 'guest') NOT NULL
```

2. The week table is deemed unnecessary as it can be managed by query with different timesatamps

```sql
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
```

3. Introduction of a task assignment section to replace the permission section in the schema.

4. A trigger has been added to update the total contributions automatically:

```sql
DELIMITER //
CREATE TRIGGER update_total_contributions AFTER INSERT ON contributions
FOR EACH ROW
BEGIN
    UPDATE users
    SET total_contributions = total_contributions + 1
    WHERE user_id = NEW.user_id;
END;
//
DELIMITER ; 
total_contributions INT DEFAULT 0
```

These changes optimize the schema by reducing redundancy and improving efficiency.  

Here is an ER diagram for better demonstration:
er diagram

### CODE REVIEW

**Comment by manwar** [comment]
@soniyaprasad77 please move css and js files to "public/" folder.

With regard to changes to contributions table, I am not sure if it is good idea. Please explain in more detail.
Think of a situation, a user shared solutions to say week w1 and task t1 in lang l1, lang l2.
Then a day later the same user shared solutions to week w1, task t2 in lang l1.
How would store this information?

**Comment by soniyadotp** [comment]
The approach I've implemented resembles the one used for displaying user ages. Instead of storing the age directly in the database, we store the user's birth date. Then, at query time, we calculate the age by subtracting the birth date from the current date. Similarly, for the four scenarios you've provided regarding Task 1, we store the timestamp created_at. This allows us to identify the week of the task. 

When a user submits their contribution to Task 1, we store the task ID and the timestamp of the contribution. This enables us to track how much time has elapsed since the task was created. With this schema, there should be no issue with users submitting multiple contributions for the same task. However, I haven't yet implemented the language part, but that will be addressed in the next pull request.

**Comment by manwar** [comment]
@soniyaprasad77, in real world, user sometimes submit contribution outside of the allotted week. For example, in the week 100, a user might decide to submit solutions to week 80 he missed for some reason.

The system should still consider solution belongs to week 80, although it was submitted in week 100. How would you handle this?

Let's keep the discussion on.

**Comment by soniyadotp** [comment]
Certainly! I agree that it is a good case and I don't anticipate any issues. I haven't created any constraints that would prevent users from contributing late.

I would like to review my schema with the user flow architecture and provide an image in the attachment. This will help to explain the schema in greater detail.
IMG-20240317-WA0011

**Comment by soniyadotp** [comment]
Pardon, @manwar, I have created this user flow based on the current schema. However, if you find this user flow unsatisfactory, could you please provide one of your own? This way, I can design a better schema to align with your preferences.

**Comment by manwar** [comment]
@soniyaprasad77 lets get this sorted quickly. 

Let me explain you what we want and you suggest a solution to this:

1) Admin creates 2 tasks (T1 and T2) each week and make these tasks public on every Monday morning.
2) Member/Guest picks the task (T1 or T2 or both), solves it and submits the solution.

We allow member/guest to solve any past tasks (T1 or T2 or both) if they want. 
So we want to be able tag the solution to past tasks (T1 or T2 or both) of past week and not the time they submit the solution.

So when we want contributions report for any member/guest we should be able to identify week, task  and language.

There should be mechanism to identify which week belongs to a month.

So when we want monthly/yearly contributions report then we can easily get that.

task -> belongs -> week -> belongs -> month -> belongs -> year

**Pull request closed without merging**
